name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ./SmartStay
      run: dotnet restore SmartStay.sln

    - name: Build solution
      working-directory: ./SmartStay
      run: dotnet build SmartStay.sln --no-restore --configuration Release

    - name: Run tests
      working-directory: ./SmartStay
      run: dotnet test --no-build --verbosity normal --configuration Release
